name: My First CI Pipeline

# 1. Trigger: Run on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  # 2. Description of the task
  build-and-test:
    # Use the default cloud runner from GitHub
    runs-on: ubuntu-latest

    steps:
    # 3. Step one: download the repository code to the runner
    - name: figlet Check out repository code
      uses: actions/checkout@v4

    # 4. Step two: build a test Docker image
    - name: figlet Build Docker Image
      run: |
        docker build -t my-app:${{ github.sha }} .
        docker images
